name    'KyleAnderson-bios'
version '0.0.2'
source 'git://github.com/solarkennedy/puppet-bios.git'
author 'Kyle Anderson'
license 'Apache License, Version 2.0'
summary 'Puppet module for managing BIOS settings'
description 'Puppet module for managing BIOS settings'
project_page 'https://github.com/solarkennedy/puppet-bios'
